Hotfix js_variable_parser
Tutorial-Inc/ExposedParameterParser pull request #5
Opened 2020-07-15 14:43 UTC by yusukeiwabuchi

正規表現のバグを修正しました。

2020-07-15 14:44 UTC, yusukeiwabuchi commented
@chan-shiro 
`10/num/10`
このパターンだと`num`を検出できないのですが、これは無視していいですか？
それとも対応した方がよろしいでしょうか？

2020-07-15 14:50 UTC, yusukeiwabuchi commented
```
iwabuchiyusuke@iwabuchiyuuyuunoMacBook-puro ExposedParameterParser % rspec
.......................................

Finished in 0.03556 seconds (files took 0.23251 seconds to load)
39 examples, 0 failures
```

2020-07-15 15:34 UTC, chan-shiro reviewed
テストで、cannot detect のところが、どういう仕様になっているのかがわからず。検出できるようにしたのか、できないのが仕様なのか。

2020-07-15 15:34 UTC, chan-shiro commented on spec/js_variable_parser_spec.rb
> +    it "cannot detect ['num']" do
cannot detect [‘num’] ってどういう意味？テストだと　expect で検出できているように見える。

2020-07-15 15:36 UTC, yusukeiwabuchi commented on spec/js_variable_parser_spec.rb
> +    it "cannot detect ['num']" do
すいません。
コピペミスりました。

2020-07-16 00:43 UTC, yusukeiwabuchi commented on spec/js_variable_parser_spec.rb
> +    it "cannot detect ['num']" do
@chan-shiro 
修正しました。

2020-07-16 01:21 UTC, terachan3700 commented
LGTMです（apploveする権限がなかった）

2020-07-16 01:34 UTC, terachan3700 approved these changes
LGTM!

2020-07-16 02:20 UTC, ayaka-tajiri requested changes
このページに乗っている特殊文字を一通り確認しました。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions

2020-07-16 02:20 UTC, ayaka-tajiri commented on lib/exposed_parameter_parser/js_variable_parser.rb
> +        @buffer.skip(/\/.*\/[egimox]*/)
s,u,yも追加しないといけなさそうです。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_Searching_With_Flags

2020-07-16 02:22 UTC, yusukeiwabuchi commented on lib/exposed_parameter_parser/js_variable_parser.rb
> +        @buffer.skip(/\/.*\/[egimox]*/)
あざす！

2020-07-16 02:29 UTC, yusukeiwabuchi commented on lib/exposed_parameter_parser/js_variable_parser.rb
> +        @buffer.skip(/\/.*\/[egimox]*/)
修正しました。

2020-07-16 03:01 UTC, ayaka-tajiri approved these changes
LGTM👍

2020-07-16 03:10 UTC, merged

2020-07-16 03:58 UTC, ayaka-tajiri commented
@yusukeiwabuchi 
マスターにマージされたので、RCのGemfile.lockのバージョンを変更する必要があります！
すでに対応済みだったら、すいません。
https://github.com/Tutorial-Inc/robotic-crowd/blob/master/Gemfile.lock#L3

2020-07-16 04:10 UTC, terachan3700 commented
対応します

2020-07-16 04:19 UTC, yusukeiwabuchi commented
@ayaka-tajiri 
なるほど！次からそちらの対応も合わせて行うようにします。

@terachan3700 
すいません。ありがとうございます。

2020-07-16 04:24 UTC, ayaka-tajiri commented
https://github.com/Tutorial-Inc/robotic-crowd/pull/1354